version: '2'

services:
  simple-kafka-mqtt-connector:
    image: arthurgrigo/simple-kafka-mqtt-connector:0.1.0
    restart: always
    hostname: simple-kafka-mqtt-connector
    container_name: kafka-mqtt-connector
    environment:
      KAFKA_HOST: localhost #EDITME IP THROUGH WHICH THE KAFKA BROKER WILL BE REACHED
      KAFKA_PORT: 9092
      KAFKA_CLIENT_ID: simple-kafka-mqtt-connector-1
      MQTT_HOST: localhost #EDITME IP THROUGH WHICH THE MQTT BROKER WILL BE REACHED
      MQTT_PORT: 1883
      MQTT_CLIENT_ID: simple-kafka-mqtt-connector-1
      MQTT_QOS: 2
      TOPIC_MAPPING: test>>>stock
